# Reachy Mini App Configuration
# This file is used by the Reachy Mini app assistant

name: reachy-mini-ha-voice
version: 1.0.0
description: Home Assistant Voice Assistant for Reachy Mini using ESPHome protocol
author: Reachy Mini HA Voice Contributors
license: Apache-2.0

# App type: python, javascript, or web
type: python

# Main entry point
entry_point: reachy_mini_ha_voice.__main__:main

# Dependencies
dependencies:
  - aioesphomeapi==42.7.0
  - numpy>=2,<3
  - pymicro-wakeword>=2,<3
  - pyopen-wakeword>=1,<2
  - pyaudio>=0.2.11
  - zeroconf<1

# Optional dependencies for Reachy Mini integration
optional_dependencies:
  - reachy-sdk

# System requirements
system_requirements:
  - portaudio19-dev
  - build-essential
  - libportaudio2

# Configuration options
config:
  - name: device_name
    type: string
    default: "ReachyMini"
    description: "Device name for Home Assistant"
  - name: enable_reachy
    type: boolean
    default: true
    description: "Enable Reachy Mini robot integration"
  - name: audio_input_device
    type: integer
    default: null
    description: "Audio input device index"
  - name: audio_output_device
    type: integer
    default: null
    description: "Audio output device index"
  - name: wake_word
    type: string
    default: "okay_nabu"
    description: "Wake word to use"

# Ports exposed by the app
ports:
  - 6053

# Tags for categorization
tags:
  - voice
  - home-assistant
  - esphome
  - assistant