blueprint:
  name: Reachy Mini 表情自动化 / Emotion Automation - TTS关键词触发
  description: |
    根据TTS播放内容的关键词自动触发Reachy Mini机器人表情。
    支持多个表情分类,每个表情可以配置多个关键词(中英文不限)。
    当TTS播放的内容命中关键词时,自动播放对应的表情动作。
    
    Automatically trigger Reachy Mini robot expressions based on TTS keywords.
    Supports multiple emotion categories, each can be configured with multiple keywords (Chinese/English).
    When TTS content matches keywords, automatically play the corresponding expression.
    
    表情分类 / Emotion Categories:
    - 开心/高兴 / Cheerful
    - 大笑 / Laughing
    - 热情/兴奋 / Enthusiastic
    - 惊讶/惊叹 / Amazed
    - 惊讶 / Surprised
    - 爱/喜欢 / Loving
    - 感谢 / Grateful
    - 欢迎 / Welcoming
    - 乐于助人 / Helpful
    - 好奇 / Curious
    - 思考 / Thoughtful
    - 理解 / Understanding
    - 骄傲/自豪 / Proud
    - 成功 / Success
    - 悲伤 / Sad
    - 抱歉 / Oops
    - 不确定 / Uncertain
    - 困惑 / Confused
    - 害怕/恐惧 / Fear
    - 焦虑 / Anxiety
    - 愤怒 / Rage
    - 烦躁/不耐烦 / Irritated
    - 沮丧 / Frustrated
    - 厌恶 / Disgusted
    - 无聊 / Boredom
    - 疲惫 / Tired
    - 困倦/睡眠 / Sleep
    - 害羞 / Shy
    - 孤独 / Lonely
    - 放松/释然 / Relief
    - 平静 / Serenity
    - 肯定/是 / Yes
    - 否定/不 / No
    - 过来 / Come
    - 走开 / Go away
    - 跳舞 / Dance
  domain: automation
  input:
    esphome_device:
      name: ESPHome设备 / ESPHome Device
      description: 选择Reachy Mini的ESPHome设备 / Select Reachy Mini's ESPHome device
      selector:
        device:
          integration: esphome
    tts_player:
      name: Voice Assistant / Voice Assistant
      description: 选择Voice Assistant的pipeline实体(状态会变为responding)/ Select Voice Assistant pipeline entity (state becomes responding)
      selector:
        entity:
          domain: conversation
    reachy_mini_emotion:
      name: Reachy Mini表情选择器 / Reachy Mini Emotion Selector
      description: Reachy Mini机器人的表情选择器实体 / Reachy Mini robot's emotion selector entity
      selector:
        entity:
          domain: select
    cheerful_keywords:
      name: 开心/高兴 关键词 / Cheerful Keywords
      description: 触发cheerful1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger cheerful1 (comma-separated)
      default: "太棒了,太好了,好开心,真高兴,开心,高兴,快乐,棒,恭喜,真好,nice,great,awesome,wonderful,excellent,happy,congratulations,congrats,good job,well done"
    laughing_keywords:
      name: 大笑 关键词 / Laughing Keywords
      description: 触发laughing1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger laughing1 (comma-separated)
      default: "哈哈,哈哈哈,嘿嘿,呵呵,笑死,太搞笑,好笑,笑了,haha,hehe,lol,lmao,rofl,funny,hilarious"
    enthusiastic_keywords:
      name: 热情/兴奋 关键词 / Enthusiastic Keywords
      description: 触发enthusiastic1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger enthusiastic1 (comma-separated)
      default: "太激动,太兴奋,兴奋,激动,耶,太酷了,酷,fantastic,excited,exciting,yay,woohoo,cool"
    amazed_keywords:
      name: 惊讶/惊叹 关键词 / Amazed Keywords
      description: 触发amazed1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger amazed1 (comma-separated)
      default: "太神奇,神奇,不可思议,太厉害,厉害,牛,amazing,incredible,unbelievable,impressive"
    surprised_keywords:
      name: 惊讶 关键词 / Surprised Keywords
      description: 触发surprised1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger surprised1 (comma-separated)
      default: "哇,哇塞,真的吗,天啊,我的天,什么,啊,wow,really,oh my god,omg,seriously,no way"
    loving_keywords:
      name: 爱/喜欢 关键词 / Loving Keywords
      description: 触发loving1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger loving1 (comma-separated)
      default: "爱,爱你,喜欢,太爱了,可爱,萌,爱死了,love,lovely,adore,cute"
    grateful_keywords:
      name: 感谢 关键词 / Grateful Keywords
      description: 触发grateful1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger grateful1 (comma-separated)
      default: "谢谢,感谢,多谢,太感谢,非常感谢,感激,thank,thanks,appreciate,grateful"
    welcoming_keywords:
      name: 欢迎 关键词 / Welcoming Keywords
      description: 触发welcoming1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger welcoming1 (comma-separated)
      default: "欢迎,你好,早上好,下午好,晚上好,嗨,welcome,hello,hi,hey,good morning,good afternoon,good evening"
    helpful_keywords:
      name: 乐于助人 关键词 / Helpful Keywords
      description: 触发helpful1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger helpful1 (comma-separated)
      default: "当然,好的,没问题,可以,行,好啊,乐意,sure,of course,no problem,certainly,absolutely,glad to help"
    curious_keywords:
      name: 好奇 关键词 / Curious Keywords
      description: 触发curious1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger curious1 (comma-separated)
      default: "好奇,有意思,有趣,奇怪,怎么回事,curious,interesting,intriguing,wonder"
    thoughtful_keywords:
      name: 思考 关键词 / Thoughtful Keywords
      description: 触发thoughtful1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger thoughtful1 (comma-separated)
      default: "嗯,让我想想,想一想,考虑,思考,想想看,我觉得,hmm,let me think,thinking,i think,perhaps,maybe"
    understanding_keywords:
      name: 理解 关键词 / Understanding Keywords
      description: 触发understanding1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger understanding1 (comma-separated)
      default: "明白,懂了,理解,原来如此,我明白了,i see,i understand,got it,makes sense"
    proud_keywords:
      name: 骄傲/自豪 关键词 / Proud Keywords
      description: 触发proud1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger proud1 (comma-separated)
      default: "骄傲,自豪,了不起,真棒,做得好,proud,bravo"
    success_keywords:
      name: 成功 关键词 / Success Keywords
      description: 触发success1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger success1 (comma-separated)
      default: "成功,搞定,完成,做到了,success,done,finished,accomplished"
    sad_keywords:
      name: 悲伤 关键词 / Sad Keywords
      description: 触发sad1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger sad1 (comma-separated)
      default: "难过,伤心,悲伤,可惜,遗憾,唉,不幸,sad,unfortunately,too bad,pity"
    oops_keywords:
      name: 抱歉 关键词 / Oops Keywords
      description: 触发oops1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger oops1 (comma-separated)
      default: "抱歉,对不起,不好意思,糟糕,哎呀,失误,搞砸,sorry,oops,my bad,excuse me,pardon"
    uncertain_keywords:
      name: 不确定 关键词 / Uncertain Keywords
      description: 触发uncertain1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger uncertain1 (comma-separated)
      default: "不知道,不确定,不太清楚,说不准,不一定,don't know,not sure,uncertain,unsure,i'm not sure"
    confused_keywords:
      name: 困惑 关键词 / Confused Keywords
      description: 触发confused1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger confused1 (comma-separated)
      default: "困惑,迷惑,搞不懂,看不懂,不理解,晕,懵,confused,confusing,puzzled,what"
    fear_keywords:
      name: 害怕/恐惧 关键词 / Fear Keywords
      description: 触发fear1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger fear1 (comma-separated)
      default: "害怕,恐惧,可怕,吓人,担心,afraid,scared,fear,scary,frightening"
    anxiety_keywords:
      name: 焦虑 关键词 / Anxiety Keywords
      description: 触发anxiety1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger anxiety1 (comma-separated)
      default: "焦虑,紧张,忐忑,不安,anxious,nervous,worried,anxiety"
    rage_keywords:
      name: 愤怒 关键词 / Rage Keywords
      description: 触发rage1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger rage1 (comma-separated)
      default: "生气,愤怒,气死,太过分,可恶,angry,mad,rage,outrageous"
    irritated_keywords:
      name: 烦躁/不耐烦 关键词 / Irritated Keywords
      description: 触发irritated1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger irritated1 (comma-separated)
      default: "烦,烦躁,烦死了,讨厌,annoyed,irritated,annoying"
    frustrated_keywords:
      name: 沮丧 关键词 / Frustrated Keywords
      description: 触发frustrated1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger frustrated1 (comma-separated)
      default: "沮丧,挫败,郁闷,心烦,frustrated,frustrating"
    disgusted_keywords:
      name: 厌恶 关键词 / Disgusted Keywords
      description: 触发disgusted1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger disgusted1 (comma-separated)
      default: "恶心,厌恶,反感,太恶心,disgusted,disgusting,gross,yuck,eww"
    boredom_keywords:
      name: 无聊 关键词 / Boredom Keywords
      description: 触发boredom1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger boredom1 (comma-separated)
      default: "无聊,好无聊,没意思,闷,bored,boring"
    tired_keywords:
      name: 疲惫 关键词 / Tired Keywords
      description: 触发tired1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger tired1 (comma-separated)
      default: "累,好累,累了,疲惫,困,tired,exhausted,sleepy"
    sleep_keywords:
      name: 困倦/睡眠 关键词 / Sleep Keywords
      description: 触发sleep1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger sleep1 (comma-separated)
      default: "想睡,睡觉,晚安,good night,sleep,nap"
    shy_keywords:
      name: 害羞 关键词 / Shy Keywords
      description: 触发shy1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger shy1 (comma-separated)
      default: "害羞,不好意思,脸红,shy,embarrassed,blush"
    lonely_keywords:
      name: 孤独 关键词 / Lonely Keywords
      description: 触发lonely1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger lonely1 (comma-separated)
      default: "孤独,寂寞,孤单,lonely,alone"
    relief_keywords:
      name: 放松/释然 关键词 / Relief Keywords
      description: 触发relief1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger relief1 (comma-separated)
      default: "放松,松一口气,终于,幸好,还好,relief,relieved,finally,phew"
    serenity_keywords:
      name: 平静 关键词 / Serenity Keywords
      description: 触发serenity1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger serenity1 (comma-separated)
      default: "平静,安静,冷静,淡定,calm,peaceful,serene,relax"
    yes_keywords:
      name: 肯定/是 关键词 / Yes Keywords
      description: 触发yes1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger yes1 (comma-separated)
      default: "是的,对,没错,正确,嗯嗯,是啊,对的,yes,yeah,yep,correct,right,exactly"
    no_keywords:
      name: 否定/不 关键词 / No Keywords
      description: 触发no1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger no1 (comma-separated)
      default: "不是,不行,不可以,不对,错,no,nope,wrong,incorrect"
    come_keywords:
      name: 过来 关键词 / Come Keywords
      description: 触发come1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger come1 (comma-separated)
      default: "过来,来,来吧,come,come here"
    go_away_keywords:
      name: 走开 关键词 / Go Away Keywords
      description: 触发go_away1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger go_away1 (comma-separated)
      default: "走开,滚,走,go away,leave,get out"
    dance_keywords:
      name: 跳舞 关键词 / Dance Keywords
      description: 触发dance1表情的关键词(多个关键词用逗号分隔) / Keywords to trigger dance1 (comma-separated)
      default: "跳舞,舞蹈,蹦迪,dance,dancing"
    delay:
      name: 触发延迟 / Trigger Delay
      description: 检测到关键词后延迟多少秒播放表情(秒) / Delay in seconds before playing emotion after keyword detected
      default: 0
      selector:
        number:
          min: 0
          max: 5
          step: 0.5
          unit_of_measurement: "秒 / seconds"
    emotion_duration:
      name: 表情持续时间 / Emotion Duration
      description: 表情播放后多久恢复默认状态(秒) / How long to wait before returning to default state (seconds)
      default: 3
      selector:
        number:
          min: 1
          max: 10
          step: 0.5
          unit_of_measurement: "秒 / seconds"

trigger:
  - platform: state
    entity_id: !input tts_player
    to: "responding"

variables:
  esphome_dev: !input esphome_device
  tts_entity: !input tts_player
  emotion_entity: !input reachy_mini_emotion
  cheerful_list: !input cheerful_keywords
  laughing_list: !input laughing_keywords
  enthusiastic_list: !input enthusiastic_keywords
  amazed_list: !input amazed_keywords
  surprised_list: !input surprised_keywords
  loving_list: !input loving_keywords
  grateful_list: !input grateful_keywords
  welcoming_list: !input welcoming_keywords
  helpful_list: !input helpful_keywords
  curious_list: !input curious_keywords
  thoughtful_list: !input thoughtful_keywords
  understanding_list: !input understanding_keywords
  proud_list: !input proud_keywords
  success_list: !input success_keywords
  sad_list: !input sad_keywords
  oops_list: !input oops_keywords
  uncertain_list: !input uncertain_keywords
  confused_list: !input confused_keywords
  fear_list: !input fear_keywords
  anxiety_list: !input anxiety_keywords
  rage_list: !input rage_keywords
  irritated_list: !input irritated_keywords
  frustrated_list: !input frustrated_keywords
  disgusted_list: !input disgusted_keywords
  boredom_list: !input boredom_keywords
  tired_list: !input tired_keywords
  sleep_list: !input sleep_keywords
  shy_list: !input shy_keywords
  lonely_list: !input lonely_keywords
  relief_list: !input relief_keywords
  serenity_list: !input serenity_keywords
  yes_list: !input yes_keywords
  no_list: !input no_keywords
  come_list: !input come_keywords
  go_away_list: !input go_away_keywords
  dance_list: !input dance_keywords
  delay_time: !input delay
  duration_time: !input emotion_duration

action:
  - variables:
      tts_text: >-
        {{ 
          state_attr(tts_entity, 'media_content_id') | default('') 
        }}
      detected_emotion: >-
        {% set text = tts_text.lower() %}
        {% set cheerful = cheerful_list.split(',') | map('trim') | map('lower') | list %}
        {% set laughing = laughing_list.split(',') | map('trim') | map('lower') | list %}
        {% set enthusiastic = enthusiastic_list.split(',') | map('trim') | map('lower') | list %}
        {% set amazed = amazed_list.split(',') | map('trim') | map('lower') | list %}
        {% set surprised = surprised_list.split(',') | map('trim') | map('lower') | list %}
        {% set loving = loving_list.split(',') | map('trim') | map('lower') | list %}
        {% set grateful = grateful_list.split(',') | map('trim') | map('lower') | list %}
        {% set welcoming = welcoming_list.split(',') | map('trim') | map('lower') | list %}
        {% set helpful = helpful_list.split(',') | map('trim') | map('lower') | list %}
        {% set curious = curious_list.split(',') | map('trim') | map('lower') | list %}
        {% set thoughtful = thoughtful_list.split(',') | map('trim') | map('lower') | list %}
        {% set understanding = understanding_list.split(',') | map('trim') | map('lower') | list %}
        {% set proud = proud_list.split(',') | map('trim') | map('lower') | list %}
        {% set success = success_list.split(',') | map('trim') | map('lower') | list %}
        {% set sad = sad_list.split(',') | map('trim') | map('lower') | list %}
        {% set oops = oops_list.split(',') | map('trim') | map('lower') | list %}
        {% set uncertain = uncertain_list.split(',') | map('trim') | map('lower') | list %}
        {% set confused = confused_list.split(',') | map('trim') | map('lower') | list %}
        {% set fear = fear_list.split(',') | map('trim') | map('lower') | list %}
        {% set anxiety = anxiety_list.split(',') | map('trim') | map('lower') | list %}
        {% set rage = rage_list.split(',') | map('trim') | map('lower') | list %}
        {% set irritated = irritated_list.split(',') | map('trim') | map('lower') | list %}
        {% set frustrated = frustrated_list.split(',') | map('trim') | map('lower') | list %}
        {% set disgusted = disgusted_list.split(',') | map('trim') | map('lower') | list %}
        {% set boredom = boredom_list.split(',') | map('trim') | map('lower') | list %}
        {% set tired = tired_list.split(',') | map('trim') | map('lower') | list %}
        {% set sleep = sleep_list.split(',') | map('trim') | map('lower') | list %}
        {% set shy = shy_list.split(',') | map('trim') | map('lower') | list %}
        {% set lonely = lonely_list.split(',') | map('trim') | map('lower') | list %}
        {% set relief = relief_list.split(',') | map('trim') | map('lower') | list %}
        {% set serenity = serenity_list.split(',') | map('trim') | map('lower') | list %}
        {% set yes = yes_list.split(',') | map('trim') | map('lower') | list %}
        {% set no = no_list.split(',') | map('trim') | map('lower') | list %}
        {% set come = come_list.split(',') | map('trim') | map('lower') | list %}
        {% set go_away = go_away_list.split(',') | map('trim') | map('lower') | list %}
        {% set dance = dance_list.split(',') | map('trim') | map('lower') | list %}
        
        {% if cheerful | select('in', text) | list | length > 0 %}
          Cheering
        {% elif laughing | select('in', text) | list | length > 0 %}
          Laughing
        {% elif enthusiastic | select('in', text) | list | length > 0 %}
          Enthusiastic
        {% elif amazed | select('in', text) | list | length > 0 %}
          Amazed
        {% elif surprised | select('in', text) | list | length > 0 %}
          Surprised
        {% elif loving | select('in', text) | list | length > 0 %}
          Loving
        {% elif grateful | select('in', text) | list | length > 0 %}
          Grateful
        {% elif welcoming | select('in', text) | list | length > 0 %}
          Welcoming
        {% elif helpful | select('in', text) | list | length > 0 %}
          Helpful
        {% elif curious | select('in', text) | list | length > 0 %}
          Curious
        {% elif thoughtful | select('in', text) | list | length > 0 %}
          Thoughtful
        {% elif understanding | select('in', text) | list | length > 0 %}
          Understanding
        {% elif proud | select('in', text) | list | length > 0 %}
          Proud
        {% elif success | select('in', text) | list | length > 0 %}
          Success
        {% elif sad | select('in', text) | list | length > 0 %}
          Sad
        {% elif oops | select('in', text) | list | length > 0 %}
          Oops
        {% elif uncertain | select('in', text) | list | length > 0 %}
          Uncertain
        {% elif confused | select('in', text) | list | length > 0 %}
          Confused
        {% elif fear | select('in', text) | list | length > 0 %}
          Fear
        {% elif anxiety | select('in', text) | list | length > 0 %}
          Anxiety
        {% elif rage | select('in', text) | list | length > 0 %}
          Rage
        {% elif irritated | select('in', text) | list | length > 0 %}
          Irritated
        {% elif frustrated | select('in', text) | list | length > 0 %}
          Frustrated
        {% elif disgusted | select('in', text) | list | length > 0 %}
          Disgusted
        {% elif boredom | select('in', text) | list | length > 0 %}
          Boredom
        {% elif tired | select('in', text) | list | length > 0 %}
          Tired
        {% elif sleep | select('in', text) | list | length > 0 %}
          Sleep
        {% elif shy | select('in', text) | list | length > 0 %}
          Shy
        {% elif lonely | select('in', text) | list | length > 0 %}
          Lonely
        {% elif relief | select('in', text) | list | length > 0 %}
          Relief
        {% elif serenity | select('in', text) | list | length > 0 %}
          Serenity
        {% elif yes | select('in', text) | list | length > 0 %}
          Yes
        {% elif no | select('in', text) | list | length > 0 %}
          No
        {% elif come | select('in', text) | list | length > 0 %}
          Come
        {% elif go_away | select('in', text) | list | length > 0 %}
          Go away
        {% elif dance | select('in', text) | list | length > 0 %}
          Dance
        {% else %}
          None
        {% endif %}

  - condition: template
    value_template: "{{ detected_emotion != 'None' }}"

  - delay:
      seconds: "{{ delay_time }}"

  - service: select.select_option
    target:
      entity_id: !input reachy_mini_emotion
    data:
      option: "{{ detected_emotion }}"

  - delay:
      seconds: "{{ duration_time }}"

  - service: select.select_option
    target:
      entity_id: !input reachy_mini_emotion
    data:
      option: "None"

mode: restart